services:
  front:
    container_name: usinnmodeler
    image: node:16.4.2-alpine
    user: node
    working_dir: /home/app
    ports:
    - "3000:3000"
    volumes:
    - .:/home/app
    command: [sh, "-c", "npm install && npm start"]
